### ISSUE TITLE
SearchFaces throws InvalidParameterException: faceId was not found in the collection

### ISSUE THREAD

**Issue by aramashkan** [awsdocs/amazon-rekognition-developer-guide#50]
Using java library software.amazon.awssdk:rekognition:2.16.54  got strange behaviour during search face method.
Case:
1) Got 2 image. First image is man with document. Second is scan of document
2) Creating collection
3) Indexing first image and got 2 faces. 
4) calling search face (of man) for finding face from document
5) Indexing second image :
```
ixFacesResp = rkgClient.indexFaces(
                            IndexFacesRequest.builder()
                                .collectionId(tempCollectionId)
                                .image(docImage)
                                .qualityFilter(QualityFilter.NONE)
                                .detectionAttributes(Attribute.ALL)
                                .maxFaces(1)
                                .build()
```
6) calling search face (of face from indexed doc) for finding matches in previous two:
```
 if (ixFacesResp.hasFaceRecords()) {
                            val searchFaces = rkgClient.searchFaces(
                                SearchFacesRequest.builder()
                                    .faceId(ixFacesResp.faceRecords()[0].face().faceId())
                                    .collectionId(tempCollectionId)
                                    .build()
                            )
}
```
Receive:
```
software.amazon.awssdk.services.rekognition.model.InvalidParameterException: faceId was not found in the collection. (Service: Rekognition, Status Code: 400, Request ID: 2954c06f-5b32-4ed3-ad21-ebe339e93dd4, Extended Request ID: null)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:123)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:79)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:59)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:30)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:73)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:50)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:36)
........
```
How it possible if i successfully received ixFacesResp at previous step and got non empty collection of matches ?
And it never fails at step 4 in spite of same code calling. Is it possible of getting Face object but empty faceId field ?

Wanted to post it in aws forums but due to 'hell' of registration, temporary can't do it.

**Comment by dnelsamz** [comment]
Hello, I'm sorry to hear you had trouble posting this issue at the AWS Forums. This isn't a documentation issue, but I recognize you are looking for help solving the problem you're having with the code. The primary place to go to get your questions answered is now the RePost forum:

https://repost.aws/

My apologies that it took so long to respond to this issue. Thank you for taking the time to comment.
